import { createEmptyReadingAnalysisStore, READING_ANALYSIS_STORE_VERSION, type ReadingAnalysisStore } from "./analysisTypes";

const text = (value: unknown, max = 20000): string => typeof value === "string" ? value.trim().slice(0, max) : "";
const list = (value: unknown, max = 100): string[] => Array.isArray(value) ? value.filter((item): item is string => Boolean(typeof item === "string" && item.trim())).map((item) => item.trim().slice(0, 1000)).slice(0, max) : [];
const scopeValid = (value: { userIdentityId?: unknown; bookId?: unknown }): boolean => typeof value.userIdentityId === "string" && Boolean(value.userIdentityId.trim()) && typeof value.bookId === "string" && Boolean(value.bookId.trim());

export function normalizeReadingAnalysisStore(value: unknown): ReadingAnalysisStore {
  if (!value || typeof value !== "object" || Array.isArray(value)) return createEmptyReadingAnalysisStore();
  const source = value as Record<string, unknown>;
  const tasks = Array.isArray(source.tasks) ? source.tasks.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object" && !Array.isArray(item))).filter(scopeValid).map((item) => ({ ...item, version: undefined, userIdentityId: item.userIdentityId as string, bookId: item.bookId as string, id: text(item.id, 200), type: item.type, status: item.status, inputVersion: text(item.inputVersion, 200), chapterIds: list(item.chapterIds), completedChapterIds: list(item.completedChapterIds), checkpointIndex: Math.max(0, Number(item.checkpointIndex) || 0), attempts: Math.max(0, Number(item.attempts) || 0), createdAt: Number(item.createdAt) || Date.now(), updatedAt: Number(item.updatedAt) || Date.now() })).filter((item) => item.id && ["chapter_summary", "entity_index", "book_bible"].includes(String(item.type)) && ["queued", "running", "completed", "failed", "cancelled"].includes(String(item.status))) : [];
  const chapterSummaries = Array.isArray(source.chapterSummaries) ? source.chapterSummaries.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object" && !Array.isArray(item))).filter(scopeValid).map((item) => ({ ...item, id: text(item.id, 200), userIdentityId: item.userIdentityId as string, bookId: item.bookId as string, chapterId: text(item.chapterId, 200), chapterOrder: Math.max(0, Number(item.chapterOrder) || 0), title: text(item.title, 500), summary: text(item.summary), keyPoints: list(item.keyPoints, 30), sourceHash: text(item.sourceHash, 200), analysisVersion: text(item.analysisVersion, 100), createdAt: Number(item.createdAt) || Date.now(), updatedAt: Number(item.updatedAt) || Date.now() })).filter((item) => item.id && item.chapterId && item.summary) : [];
  const entities = Array.isArray(source.entities) ? source.entities.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object" && !Array.isArray(item))).filter(scopeValid).map((item) => ({ ...item, id: text(item.id, 200), userIdentityId: item.userIdentityId as string, bookId: item.bookId as string, kind: item.kind, name: text(item.name, 300), aliases: list(item.aliases, 30), summary: text(item.summary), chapterIds: list(item.chapterIds, 200), attributes: typeof item.attributes === "object" && item.attributes && !Array.isArray(item.attributes) ? Object.fromEntries(Object.entries(item.attributes).filter(([, value]) => typeof value === "string").slice(0, 30).map(([key, value]) => [key.slice(0, 100), String(value).slice(0, 1000)])) : {}, confidence: Math.min(1, Math.max(0, Number(item.confidence) || 0)), analysisVersion: text(item.analysisVersion, 100), createdAt: Number(item.createdAt) || Date.now(), updatedAt: Number(item.updatedAt) || Date.now() })).filter((item) => item.id && ["character", "location", "faction", "event"].includes(String(item.kind)) && item.name) : [];
  const bookBibles = Array.isArray(source.bookBibles) ? source.bookBibles.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object" && !Array.isArray(item))).filter(scopeValid).map((item) => ({ ...item, id: text(item.id, 200), userIdentityId: item.userIdentityId as string, bookId: item.bookId as string, version: Math.max(1, Number(item.version) || 1), analysisVersion: text(item.analysisVersion, 100), premise: text(item.premise, 4000), worldRules: list(item.worldRules, 100), storyLines: list(item.storyLines, 100), coreCharacterIds: list(item.coreCharacterIds, 200), keyLocationIds: list(item.keyLocationIds, 200), keyFactionIds: list(item.keyFactionIds, 200), timeline: list(item.timeline, 200), isUserEdited: Boolean(item.isUserEdited), createdAt: Number(item.createdAt) || Date.now(), updatedAt: Number(item.updatedAt) || Date.now() })).filter((item) => item.id) : [];
  return { version: READING_ANALYSIS_STORE_VERSION, tasks: tasks as ReadingAnalysisStore["tasks"], chapterSummaries: chapterSummaries as ReadingAnalysisStore["chapterSummaries"], entities: entities as ReadingAnalysisStore["entities"], bookBibles: bookBibles as ReadingAnalysisStore["bookBibles"] };
}
