import { createEmptyReadingStoryStore, READING_STORY_STORE_VERSION, type ReadingStoryStore } from "./storyTypes";

const text = (value: unknown, max = 12000): string => typeof value === "string" ? value.trim().slice(0, max) : "";
const list = (value: unknown, max = 100): string[] => Array.isArray(value) ? value.filter((item): item is string => Boolean(typeof item === "string" && item.trim())).map((item) => item.trim().slice(0, 1000)).slice(0, max) : [];
const scopeValid = (item: Record<string, unknown>): boolean => typeof item.userIdentityId === "string" && Boolean(item.userIdentityId.trim());

export function normalizeReadingStoryStore(value: unknown): ReadingStoryStore {
  if (!value || typeof value !== "object" || Array.isArray(value)) return createEmptyReadingStoryStore();
  const source = value as Record<string, unknown>;
  const stories = Array.isArray(source.stories) ? source.stories.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object" && !Array.isArray(item))).filter(scopeValid).map((item) => ({ ...item, userIdentityId: item.userIdentityId as string, storyId: text(item.storyId, 200), title: text(item.title, 500), entryMode: item.entryMode, status: item.status, length: item.length, targetChapters: Math.max(1, Number(item.targetChapters) || 1), currentChapter: Math.max(0, Number(item.currentChapter) || 0), currentLocation: text(item.currentLocation, 500), currentTime: text(item.currentTime, 200), characterName: text(item.characterName, 200), characterRole: text(item.characterRole, 500) || undefined, goals: list(item.goals, 30), discoveredIntel: list(item.discoveredIntel, 100), tasks: list(item.tasks, 100), relationships: typeof item.relationships === "object" && item.relationships && !Array.isArray(item.relationships) ? Object.fromEntries(Object.entries(item.relationships).filter(([, value]) => Number.isFinite(Number(value))).slice(0, 100).map(([key, value]) => [key.slice(0, 200), Math.max(-100, Math.min(100, Number(value)))])) : {}, inventory: list(item.inventory, 100), createdAt: Number(item.createdAt) || Date.now(), updatedAt: Number(item.updatedAt) || Date.now() })).filter((item) => item.storyId && item.title && ["soul_wear", "body_wear"].includes(String(item.entryMode)) && ["active", "completed", "paused", "abandoned"].includes(String(item.status)) && ["short", "medium", "long"].includes(String(item.length))) : [];
  const turns = Array.isArray(source.turns) ? source.turns.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object" && !Array.isArray(item))).filter(scopeValid).map((item) => ({ ...item, userIdentityId: item.userIdentityId as string, storyId: text(item.storyId, 200), id: text(item.id, 200), turnIndex: Math.max(0, Number(item.turnIndex) || 0), parentTurnId: text(item.parentTurnId, 200) || undefined, narrative: text(item.narrative), dialogue: Array.isArray(item.dialogue) ? item.dialogue.filter((entry): entry is Record<string, unknown> => Boolean(entry && typeof entry === "object" && !Array.isArray(entry))).slice(0, 50).map((entry) => ({ speaker: text(entry.speaker, 200), text: text(entry.text, 2000) })).filter((entry) => entry.speaker && entry.text) : [], choices: Array.isArray(item.choices) ? item.choices.filter((entry): entry is Record<string, unknown> => Boolean(entry && typeof entry === "object" && !Array.isArray(entry))).slice(0, 8).map((entry) => ({ id: text(entry.id, 100), label: text(entry.label, 500), consequenceHint: text(entry.consequenceHint, 500) || undefined })).filter((entry) => entry.id && entry.label) : [], userAction: text(item.userAction, 2000) || undefined, stateChanges: list(item.stateChanges, 50), discoveredIntel: list(item.discoveredIntel, 50), taskChanges: list(item.taskChanges, 50), relationshipChanges: list(item.relationshipChanges, 50), currentLocation: text(item.currentLocation, 500), currentTime: text(item.currentTime, 200), chapterProgress: Math.max(0, Math.min(1, Number(item.chapterProgress) || 0)), shouldEndChapter: Boolean(item.shouldEndChapter), createdAt: Number(item.createdAt) || Date.now() })).filter((item) => item.id && item.storyId && item.narrative) : [];
  const saves = Array.isArray(source.saves) ? source.saves.filter((item): item is Record<string, unknown> => Boolean(item && typeof item === "object" && !Array.isArray(item))).filter(scopeValid).map((item) => ({ ...item, userIdentityId: item.userIdentityId as string, storyId: text(item.storyId, 200), id: text(item.id, 200), turnId: text(item.turnId, 200), label: text(item.label, 300), state: item.state, createdAt: Number(item.createdAt) || Date.now() })).filter((item) => item.id && item.storyId && item.turnId && item.label && item.state && typeof item.state === "object") : [];
  return { version: READING_STORY_STORE_VERSION, stories: stories as ReadingStoryStore["stories"], turns: turns as ReadingStoryStore["turns"], saves: saves as ReadingStoryStore["saves"] };
}
