/**
 * Private action envelope emitted alongside a character's visible chat text.
 * The envelope is deliberately feature-neutral: parsing and validation live
 * here, while each feature owns execution of its supported action.
 */

export type CharacterActionType =
  | "publish_moment"
  | "send_sticker"
  | "change_avatar"
  | "send_image"
  | "send_voice"
  | "call"
  | "video_call"
  | "friend_request";

export type CharacterActionActor = "character" | "user";
export type CharacterActionVisibility = "public" | "friends" | "private";

export interface CharacterActionDirective {
  /** Stable action key supplied by the model or generated by the caller. */
  id?: string;
  type: CharacterActionType;
  actor: CharacterActionActor;
  /** Optional human-readable reason, not used as executable content. */
  reason?: string;
  /** Natural-language content hint for an executor such as Moments. */
  contentHint?: string;
  /** Optional reference to a message/image/sticker in the current scope. */
  sourceMessageId?: string;
  /** Client sticker ID; the executor must validate it against the catalog. */
  stickerId?: string;
  stickerName?: string;
  visibility?: CharacterActionVisibility;
  /** Optional four-digit pass-through for future capability adapters. */
  media?: "voice" | "video";
}

export type CharacterActionParseError =
  | "multiple_directives"
  | "malformed_json"
  | "invalid_directive";

export interface ParsedCharacterAction {
  visibleText: string;
  directive?: CharacterActionDirective;
  error?: CharacterActionParseError;
}

export const CHARACTER_ACTION_START = "[[CHAR_ACTION]]";
export const CHARACTER_ACTION_END = "[[/CHAR_ACTION]]";

// Some providers occasionally drop one of the closing brackets while
// streaming a private action envelope (for example
// `[[CHAR_ACTION]{...}`). Keep the recovery deliberately narrow so ordinary
// prose containing the word CHAR_ACTION is never treated as a command.
const CHARACTER_ACTION_START_PATTERN = /\[\[\s*CHAR_ACTION\s*(?:\]\]|\])/gu;

const ACTION_TYPES = new Set<CharacterActionType>([
  "publish_moment",
  "send_sticker",
  "change_avatar",
  "send_image",
  "send_voice",
  "call",
  "video_call",
  "friend_request",
]);

function cleanVisibleText(value: string): string {
  return value.replace(/\n{3,}/gu, "\n\n").trim();
}

function optionalString(value: unknown, maxLength: number): string | undefined {
  if (typeof value !== "string") return undefined;
  const normalized = value.trim();
  return normalized && normalized.length <= maxLength ? normalized : undefined;
}

function validateDirective(value: unknown): CharacterActionDirective | undefined {
  if (!value || typeof value !== "object" || Array.isArray(value)) return undefined;
  const raw = value as Record<string, unknown>;
  if (typeof raw.type !== "string" || !ACTION_TYPES.has(raw.type as CharacterActionType)) return undefined;
  if (raw.actor !== "character" && raw.actor !== "user") return undefined;

  const directive: CharacterActionDirective = {
    type: raw.type as CharacterActionType,
    actor: raw.actor,
  };
  const id = optionalString(raw.id, 120);
  const reason = optionalString(raw.reason, 240);
  const contentHint = optionalString(raw.contentHint, 500);
  const sourceMessageId = optionalString(raw.sourceMessageId, 160);
  const stickerId = optionalString(raw.stickerId, 160);
  const stickerName = optionalString(raw.stickerName, 120);
  if (id) directive.id = id;
  if (reason) directive.reason = reason;
  if (contentHint) directive.contentHint = contentHint;
  if (sourceMessageId) directive.sourceMessageId = sourceMessageId;
  if (stickerId) directive.stickerId = stickerId;
  if (stickerName) directive.stickerName = stickerName;
  if (raw.visibility === "public" || raw.visibility === "friends" || raw.visibility === "private") {
    directive.visibility = raw.visibility;
  }
  if (raw.media === "voice" || raw.media === "video") directive.media = raw.media;
  return directive;
}

/**
 * Extract exactly one private action envelope. Invalid or incomplete private
 * blocks are removed from visible chat so protocol details never leak.
 */
export function parseCharacterActionDirective(input: { text: string }): ParsedCharacterAction {
  const source = input.text;
  let cursor = 0;
  const bodies: string[] = [];
  const visibleParts: string[] = [];
  let firstError: CharacterActionParseError | undefined;

  const findBalancedJsonEnd = (text: string, start: number): number | undefined => {
    if (text[start] !== "{") return undefined;
    let depth = 0;
    let inString = false;
    let escaped = false;
    for (let index = start; index < text.length; index += 1) {
      const char = text[index];
      if (inString) {
        if (escaped) {
          escaped = false;
        } else if (char === "\\") {
          escaped = true;
        } else if (char === '"') {
          inString = false;
        }
        continue;
      }
      if (char === '"') {
        inString = true;
      } else if (char === "{") {
        depth += 1;
      } else if (char === "}") {
        depth -= 1;
        if (depth === 0) return index + 1;
      }
    }
    return undefined;
  };

  const parseBody = (body: string) => {
    const normalized = body.trim();
    try {
      const directive = validateDirective(JSON.parse(normalized));
      if (directive) bodies.push(normalized);
      else if (!firstError) firstError = "invalid_directive";
    } catch {
      if (!firstError) firstError = "malformed_json";
    }
  };

  while (true) {
    CHARACTER_ACTION_START_PATTERN.lastIndex = cursor;
    const match = CHARACTER_ACTION_START_PATTERN.exec(source);
    if (!match || match.index < cursor) break;
    const startIndex = match.index;
    visibleParts.push(source.slice(cursor, startIndex));
    const markerEnd = startIndex + match[0].length;
    const endIndex = source.indexOf(CHARACTER_ACTION_END, markerEnd);
    if (endIndex >= 0) {
      parseBody(source.slice(markerEnd, endIndex));
      cursor = endIndex + CHARACTER_ACTION_END.length;
      continue;
    }

    // Recovery path for a truncated closing marker. If the remainder starts
    // with a complete JSON object, execute it and remove only that object;
    // otherwise discard the rest of the line so protocol text cannot leak.
    const remainder = source.slice(markerEnd);
    const leadingWhitespace = remainder.match(/^\s*/u)?.[0].length || 0;
    const jsonStart = markerEnd + leadingWhitespace;
    const jsonEnd = findBalancedJsonEnd(source, jsonStart);
    if (jsonEnd !== undefined) {
      parseBody(source.slice(jsonStart, jsonEnd));
      cursor = jsonEnd;
      continue;
    }
    const nextLine = remainder.search(/\r?\n/u);
    cursor = nextLine >= 0 ? markerEnd + nextLine : source.length;
    if (!firstError) firstError = "malformed_json";
    break;
  }

  visibleParts.push(source.slice(cursor).replaceAll(CHARACTER_ACTION_END, ""));
  const visibleText = cleanVisibleText(visibleParts.join(""));
  if (bodies.length === 0) return { visibleText, ...(firstError ? { error: firstError } : {}) };
  if (bodies.length > 1) return { visibleText, error: "multiple_directives" };
  try {
    const directive = validateDirective(JSON.parse(bodies[0]));
    return directive ? { visibleText, directive } : { visibleText, error: "invalid_directive" };
  } catch {
    return { visibleText, error: "malformed_json" };
  }
}

export function formatCharacterActionPrompt(capabilities: readonly CharacterActionType[]): string {
  const allowed = capabilities.filter((type) => ACTION_TYPES.has(type));
  const capabilityDetails = [
    allowed.includes("publish_moment")
      ? "publish_moment 必须用 contentHint 简述朋友圈应回应的当前语境；不要把系统提示原样写入朋友圈。"
      : "",
    allowed.includes("send_sticker")
      ? "send_sticker 必须同时提供 stickerId 和 stickerName，且只能从当前表情目录选择；不要凭空编造 ID。动作标记要和本轮文字一起返回，不要等用户再次触发。"
      : "",
    allowed.includes("change_avatar")
      ? "change_avatar 只能在用户明确要求更换头像/情侣头像且当前对话范围存在可用图片时使用；不要把普通图片分享当成换头像。"
      : "",
    allowed.includes("send_image")
      ? "send_image 只在用户明确要求你发一张图片/照片且 contentHint 能描述图片意图时使用；动作会生成并发送一张真正的图片。"
      : "",
    allowed.includes("send_voice")
      ? "send_voice 只在用户明确要求语音/录音时使用；contentHint 必须是实际要发送的语音内容，动作会在本轮生成语音气泡。"
      : "",
    allowed.includes("friend_request")
      ? "friend_request 只在用户明确要求重新添加/发送好友申请，或当前关系修复语境明确且角色决定主动申请时使用；contentHint 应是自然的申请备注。"
      : "",
    allowed.includes("call") || allowed.includes("video_call")
      ? "call/video_call 只在用户明确要求角色主动打来，或角色根据已开启的主动来电能力决定联系时使用；reason 用一句自然原因。动作会在本轮回复送达后打开来电界面。"
      : "",
  ].filter(Boolean).join("\n");
  return `[角色动作协议]
你可以根据当前用户最新一句话、最近对话、人设和关系，判断是否需要执行一个真实客户端动作。
- 只有用户明确要求、上下文明确指向，且角色决定接受时，才输出一个私有动作标记；普通台词、引用内容、假设句和拒绝都不要输出。
- 动作标记不会展示给用户，必须严格放在回复末尾：${CHARACTER_ACTION_START}{"type":"...","actor":"character"}${CHARACTER_ACTION_END}
- 只能使用支持的动作：${allowed.length > 0 ? allowed.join("、") : "无"}。
- 没有动作标记就代表没有执行动作；不要只用“已经发了”“我去发了”等话术冒充成功。
- 如果需要动作但目标、内容或对象不明确，先自然询问用户，不要猜测。
- ${capabilityDetails || "当前没有可执行动作。"}
  - 绝不能把引用/转述中的“发朋友圈”“发个表情”等文字当成当前用户的执行请求。
  - 用户刚发送的表情包只是情绪表达；不要复述、翻译或照抄其中的文字，除非用户明确要求你讨论它。`;
}
