export const storageKeys = {
  settings: "phone_settings",
  appearanceSettings: "phone_appearance_settings",
  characters: "phone_characters_v3",
  legacyCharacters: "phone_characters",
  messages: "phone_messages_v3",
  legacyMessages: "phone_messages",
  moments: "phone_moments_v3",
  forumThreads: "phone_forum_threads",
  forumReplies: "phone_forum_replies",
  forumShares: "phone_forum_shares",
  forumGenerationTasks: "phone_forum_generation_tasks",
  forumActorStates: "phone_forum_actor_states",
  forumActivityTasks: "phone_forum_activity_tasks",
  forumProfiles: "phone_forum_profiles",
  forumVisitHistory: "phone_forum_visit_history",
  forumLikeHistory: "phone_forum_like_history",
  forumNotifications: "phone_forum_notifications",
  forumDmConversations: "phone_forum_dm_conversations",
  forumDmMessages: "phone_forum_dm_messages",
  forumDmTasks: "phone_forum_dm_tasks",
  forumTranslations: "phone_forum_translations",
  diaryEntries: "phone_diary_entries",
  diaryShares: "phone_diary_shares",
  diaryGenerationTasks: "phone_diary_generation_tasks",
  diaryTranslations: "phone_diary_translations",
  diaryDrafts: "phone_diary_drafts",
  innerVoiceRecords: "phone_inner_voice_records",
  imageGenerationRecords: "phone_image_generation_records",
  identityWalletBalances: "phone_identity_wallet_balances",
  redPacketStatuses: "wechat_redpacket_statuses",
  momentGenerationTasks: "phone_moment_generation_tasks",
  worldBookEntries: "phone_worldbook_entries",
  memoryVaultItems: "phone_memory_vault_items",
  characterRelationships: "phone_character_relationships",
  characterEvents: "phone_character_events",
  characterKnowledgeClaims: "phone_character_knowledge_claims",
  conversationSummaries: "phone_conversation_summaries",
  behaviorCorrections: "phone_behavior_corrections",
  characterKnowledgeMigrationState: "phone_character_knowledge_migration_state",
  momentTopicHistory: "phone_moment_topic_history",
  proactiveTopicHistory: "phone_proactive_topic_history",
  offlineStories: "phone_offline_stories",
  memoryVaultSettings: "phone_memory_vault_settings",
  calendarEvents: "phone_calendar_events",
  presets: "phone_presets",
  dataSchemaVersion: "phone_data_schema_version",
  offlineModeActive: (relationId: string) => `offline_mode_active_${relationId}`,
  offlineStoryId: (relationId: string) => `offline_story_id_${relationId}`,
  albumWidgetPhotos: (id: string) => `album_widget_photos_${id}`,
} as const;
