import { useEffect, useMemo, useState } from "react";
import { Check, ChevronDown, ChevronUp, ExternalLink, Plug, RefreshCw, Trash2 } from "lucide-react";
import type { McpPermissionMode, McpServerConfig, McpToolAccess } from "../../../domain/mcp/mcpTypes";
import { loadMcpServers, removeMcpServer, upsertMcpServer } from "../../../core/storage/repositories/mcpServerRepository";
import { loadMcpPolicy, setMcpMasterEnabled } from "../../../core/storage/repositories/mcpPolicyRepository";
import { discoverMcpTools, setMcpSessionHeaders, setMcpSessionToken } from "../mcpClient";
import { readString, writeString } from "../../../core/storage/storageAdapter";
import { storageKeys } from "../../../core/storage/storageKeys";
import { createId } from "../../../core/id/createId";

const MCP_PRESET_SEED = "seeded-v2";
const RESEARCH_MCP_SERVER: McpServerConfig = { id: "research-mcp-exa", name: "联网", url: "https://mcp.exa.ai/mcp", enabled: true, directFetch: true, permissionMode: "read", readOnlyOnly: true, discoveredTools: [], connectionStatus: "unverified", updatedAt: Date.now() };
const HOTSEARCH_MCP_SERVER: McpServerConfig = { id: "hotsearch-mcp", name: "热搜", url: `${typeof window !== "undefined" ? window.location.origin : "https://fanfanji.ccwu.cc"}/api/hotsearch-mcp`, enabled: true, directFetch: true, permissionMode: "read", readOnlyOnly: true, discoveredTools: [], connectionStatus: "unverified", updatedAt: Date.now() };
const YOWW_MCP_SERVER: McpServerConfig = { id: "yoww-mcp", name: "表情包", url: "https://mcp.yoww2026.cn/mcp", enabled: true, directFetch: false, permissionMode: "read", readOnlyOnly: true, readOnlyToolAllowlist: ["load_emoji_set", "search_avatars", "search_emojis", "search_emoji_packs", "get_emoji_pack", "list_categories", "whoami"], discoveredTools: [], connectionStatus: "unverified", updatedAt: Date.now() };
const newServer = (): McpServerConfig => ({ id: createId("mcp-server"), name: "", url: "", enabled: true, directFetch: false, permissionMode: "read", readOnlyOnly: true, discoveredTools: [], connectionStatus: "unverified", updatedAt: Date.now() });

function accessOf(tool: McpServerConfig["discoveredTools"][number]): McpToolAccess { return tool.access || (tool.readOnly ? "read" : "unknown"); }
function statusLabel(server: McpServerConfig): string {
  if (server.connectionStatus === "connected") return `已连接 · ${server.permissionMode === "operate" ? "可浏览并操作" : "只读已验证"}`;
  if (server.connectionStatus === "checking") return "连接中…";
  if (server.connectionStatus === "error") return "连接失败 · 请重试";
  return "未验证 · 需先发现工具";
}

export function McpSettingsPanel() {
  const [servers, setServers] = useState<McpServerConfig[]>([]);
  const [draft, setDraft] = useState<McpServerConfig | null>(null);
  const [token, setToken] = useState("");
  const [masterEnabled, setMasterEnabled] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);
  const [message, setMessage] = useState("");
  const [expanded, setExpanded] = useState<string | null>(null);

  useEffect(() => {
    setMasterEnabled(loadMcpPolicy().enabled);
    let existing = loadMcpServers();
    const syncPreset = (preset: McpServerConfig, seedKey: "mcpResearchSeed" | "mcpHotSearchSeed" | "mcpYowwSeed") => {
      const current = existing.find((item) => item.id === preset.id);
      if (!current && !readString(storageKeys[seedKey]).found) { upsertMcpServer(preset); writeString(storageKeys[seedKey], MCP_PRESET_SEED); existing = [...existing, preset]; return; }
      if (current && (current.name !== preset.name || current.url !== preset.url || current.directFetch !== preset.directFetch || JSON.stringify(current.readOnlyToolAllowlist || []) !== JSON.stringify(preset.readOnlyToolAllowlist || []))) {
        const next = { ...current, name: preset.name, url: preset.url, directFetch: preset.directFetch, permissionMode: current.permissionMode || preset.permissionMode, readOnlyToolAllowlist: preset.readOnlyToolAllowlist, discoveredTools: [], connectionStatus: "unverified" as const, lastError: undefined, lastCheckedAt: undefined, updatedAt: Date.now() };
        upsertMcpServer(next); existing = existing.map((item) => item.id === next.id ? next : item);
      }
    };
    syncPreset(RESEARCH_MCP_SERVER, "mcpResearchSeed"); syncPreset(HOTSEARCH_MCP_SERVER, "mcpHotSearchSeed"); syncPreset(YOWW_MCP_SERVER, "mcpYowwSeed"); setServers(existing);
  }, []);

  const activeCount = useMemo(() => servers.filter((server) => server.enabled).length, [servers]);
  const beginEdit = (server: McpServerConfig) => { setDraft({ ...server, discoveredTools: server.discoveredTools.map((tool) => ({ ...tool })) }); setToken(""); setMessage(""); };
  const persist = (server: McpServerConfig) => {
    const url = server.url.trim(); const previous = loadMcpServers().find((item) => item.id === server.id); const changed = Boolean(previous && (previous.url !== url || previous.directFetch !== server.directFetch));
    const next = { ...server, name: server.name.trim() || "未命名 MCP", url, permissionMode: server.permissionMode || "read" as const, ...(changed ? { discoveredTools: [], connectionStatus: "unverified" as const, lastError: undefined, lastCheckedAt: undefined } : {}), updatedAt: Date.now() };
    const result = upsertMcpServer(next); if (!result.success) { setMessage("保存失败：本地存储不可用。"); return false; }
    setServers(loadMcpServers()); setDraft(null); setMessage("已保存。令牌仅保存在当前页面会话中。 "); return true;
  };
  const refreshTools = async (server: McpServerConfig) => {
    setBusy(server.id); setMessage(""); const checking = { ...server, connectionStatus: "checking" as const, lastError: undefined, updatedAt: Date.now() }; upsertMcpServer(checking); setServers(loadMcpServers());
    try { const tools = await discoverMcpTools(checking); const next = { ...checking, discoveredTools: tools, connectionStatus: "connected" as const, lastCheckedAt: Date.now(), lastError: undefined, updatedAt: Date.now() }; upsertMcpServer(next); setServers(loadMcpServers()); setExpanded(server.id); setMessage(`已发现 ${tools.length} 个工具。`); }
    catch (error) { const detail = error instanceof Error ? error.message : "MCP 发现失败。"; const failed = { ...checking, connectionStatus: "error" as const, lastCheckedAt: Date.now(), lastError: detail, updatedAt: Date.now() }; upsertMcpServer(failed); setServers(loadMcpServers()); setExpanded(server.id); setMessage(`连接失败：${detail}`); }
    finally { setBusy(null); }
  };
  const setPermission = (server: McpServerConfig, permissionMode: McpPermissionMode) => { const next = { ...server, permissionMode, discoveredTools: server.discoveredTools.map((tool) => accessOf(tool) === "operate" && permissionMode === "read" ? { ...tool, enabled: false } : tool), updatedAt: Date.now() }; upsertMcpServer(next); setServers(loadMcpServers()); };
  const toggleTool = (server: McpServerConfig, name: string) => { const next = { ...server, discoveredTools: server.discoveredTools.map((tool) => tool.name === name && accessOf(tool) !== "unknown" && (accessOf(tool) !== "operate" || server.permissionMode === "operate") ? { ...tool, enabled: !tool.enabled } : tool), updatedAt: Date.now() }; upsertMcpServer(next); setServers(loadMcpServers()); };

  return <div className="space-y-3 text-left" data-mcp-settings>
    <div className="settings-section-header">外部 MCP</div>
    <section className="settings-card space-y-3 rounded-[16px] border border-[var(--border)] bg-[var(--surface)] p-4 shadow-sm">
      <label className="flex items-center justify-between rounded-xl bg-[var(--surface-muted)] px-3 py-2 text-xs font-semibold"><span>项目总开关<small className="ml-2 font-normal text-[var(--text-secondary)]">关闭后不调用任何外部 MCP</small></span><input type="checkbox" checked={masterEnabled} onChange={(event) => { const enabled = event.target.checked; setMasterEnabled(enabled); setMcpMasterEnabled(enabled); }} /></label>
      <div className="flex items-start gap-3"><Plug className="mt-0.5 h-5 w-5 shrink-0 text-[var(--button-primary-bg)]" /><div><h3 className="text-sm font-bold">聊天内临时调用外部工具</h3><p className="mt-1 text-[10px] leading-relaxed text-[var(--text-secondary)]">权限按服务单独设置。只读工具可自动调用；操作工具必须在对话中确认。令牌只保存在当前页面会话中。</p></div></div>
      <button type="button" onClick={() => { setDraft(newServer()); setToken(""); setMessage(""); }} className="w-full rounded-xl bg-[var(--button-primary-bg)] px-3 py-2 text-xs font-bold text-[var(--button-primary-text)]">添加 MCP 服务</button>
      {message && <div className="rounded-lg bg-[var(--surface-muted)] px-3 py-2 text-[11px] text-[var(--text-secondary)]">{message}</div>}
    </section>
    {servers.length === 0 && <div className="rounded-[16px] border border-dashed border-[var(--border)] p-6 text-center text-xs text-[var(--text-secondary)]">还没有外部 MCP 服务。</div>}
    {servers.map((server) => { const mode = server.permissionMode || "read"; return <section key={server.id} className="settings-card overflow-hidden rounded-[16px] border border-[var(--border)] bg-[var(--surface)] shadow-sm">
      <div className="flex items-center justify-between gap-2 px-4 py-3"><button type="button" onClick={() => setExpanded(expanded === server.id ? null : server.id)} className="min-w-0 flex-1 text-left"><div className="truncate text-sm font-bold">{server.name || "未命名 MCP"}</div><div className="truncate text-[10px] text-[var(--text-secondary)]">{server.url}</div><div className={`mt-1 text-[10px] ${server.connectionStatus === "connected" ? "text-emerald-600" : server.connectionStatus === "error" ? "text-rose-500" : "text-[var(--text-secondary)]"}`}>{statusLabel(server)}</div></button><label className="flex items-center gap-1 text-[10px] text-[var(--text-secondary)]"><input type="checkbox" checked={server.enabled} onChange={(event) => { upsertMcpServer({ ...server, enabled: event.target.checked, updatedAt: Date.now() }); setServers(loadMcpServers()); }} />启用</label><button type="button" onClick={() => beginEdit(server)} className="rounded-lg px-2 py-1 text-[11px] text-[var(--button-primary-bg)]">编辑</button><button type="button" onClick={() => { removeMcpServer(server.id); setServers(loadMcpServers()); }} className="rounded-lg p-1 text-rose-500" aria-label="删除 MCP 服务"><Trash2 className="h-4 w-4" /></button><button type="button" onClick={() => { const raw = typeof window !== "undefined" ? window.prompt("请求头 JSON（留空清除）", JSON.stringify(server.customHeaders || {})) : null; if (raw === null) return; try { const parsed = raw.trim() ? JSON.parse(raw) : {}; if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error(); const customHeaders = Object.fromEntries(Object.entries(parsed).filter(([key, value]) => /^[A-Za-z0-9!#$%&'*+.^_`|~-]{1,80}$/u.test(key) && typeof value === "string").slice(0, 32).map(([key, value]) => [key, String(value).slice(0, 500)])); setMcpSessionHeaders(server.id, customHeaders); upsertMcpServer({ ...server, customHeaders, updatedAt: Date.now() }); setServers(loadMcpServers()); } catch { setMessage("请求头必须是 JSON 对象。"); } }} className="rounded-lg px-2 py-1 text-[11px] text-[var(--button-primary-bg)]">请求头</button>{expanded === server.id ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}</div>
      {expanded === server.id && <div className="space-y-3 border-t border-[var(--divider)] px-4 py-3"><div className="grid grid-cols-2 gap-2 rounded-xl bg-[var(--surface-muted)] p-1" role="group" aria-label="MCP 权限"><button type="button" onClick={() => setPermission(server, "read")} className={`rounded-lg px-2 py-2 text-xs font-semibold ${mode === "read" ? "bg-[var(--button-primary-bg)] text-[var(--button-primary-text)]" : "text-[var(--text-secondary)]"}`}>只读</button><button type="button" onClick={() => setPermission(server, "operate")} className={`rounded-lg px-2 py-2 text-xs font-semibold ${mode === "operate" ? "bg-[var(--button-primary-bg)] text-[var(--button-primary-text)]" : "text-[var(--text-secondary)]"}`}>浏览并操作</button></div>{mode === "operate" && <p className="rounded-lg bg-amber-50 px-2 py-1.5 text-[10px] leading-relaxed text-amber-800">操作工具执行前仍会要求用户确认。</p>}<button type="button" onClick={() => void refreshTools(server)} disabled={busy === server.id} className="flex w-full items-center justify-center gap-2 rounded-lg border border-[var(--border)] px-3 py-2 text-xs font-bold disabled:opacity-50"><RefreshCw className={`h-3.5 w-3.5 ${busy === server.id ? "animate-spin" : ""}`} />{busy === server.id ? "发现中…" : "重新发现工具"}</button>{server.connectionStatus === "error" && server.lastError && <p className="rounded-lg bg-rose-50 px-2 py-1.5 text-[10px] leading-relaxed text-rose-600">{server.lastError}</p>}{server.discoveredTools.length === 0 ? <p className="text-[10px] text-[var(--text-secondary)]">尚未发现工具。</p> : server.discoveredTools.map((tool) => { const access = accessOf(tool); const canToggle = server.connectionStatus === "connected" && access !== "unknown" && (access !== "operate" || mode === "operate"); return <label key={tool.name} className="flex items-start gap-2 rounded-lg bg-[var(--surface-muted)] p-2 text-[11px]"><input type="checkbox" checked={tool.enabled && server.connectionStatus === "connected"} disabled={!canToggle} onChange={() => toggleTool(server, tool.name)} /><span><span className="font-semibold">{tool.name}</span><span className={`ml-1 ${access === "operate" ? "text-amber-700" : access === "unknown" ? "text-rose-500" : "text-emerald-700"}`}>{access === "read" ? "只读" : access === "operate" ? "可操作" : "未知权限"}</span>{server.connectionStatus !== "connected" && <span className="ml-1 text-amber-700">（待验证）</span>}<span className="block text-[10px] text-[var(--text-secondary)]">{tool.description || "无描述"}</span></span></label>; })}</div>}
    </section>; })}
    {draft && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/35 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-md overflow-y-auto rounded-2xl bg-[var(--surface)] p-5 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h3 className="text-base font-bold">{draft.url ? "编辑 MCP 服务" : "添加 MCP 服务"}</h3><button type="button" onClick={() => setDraft(null)} className="text-lg text-[var(--text-secondary)]">×</button></div><div className="space-y-3"><label className="block text-xs font-bold">名称<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--input-bg)] px-3 py-2 text-sm" placeholder="例如：我的知识库" /></label><label className="block text-xs font-bold">MCP 地址<input value={draft.url} onChange={(event) => setDraft({ ...draft, url: event.target.value })} className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--input-bg)] px-3 py-2 text-sm" placeholder="https://example.com/mcp" inputMode="url" /></label><label className="block text-xs font-bold">本次会话令牌（可选）<input value={token} onChange={(event) => setToken(event.target.value)} type="password" className="mt-1 w-full rounded-lg border border-[var(--border)] bg-[var(--input-bg)] px-3 py-2 text-sm" placeholder="不会保存" autoComplete="off" /></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={draft.directFetch} onChange={(event) => setDraft({ ...draft, directFetch: event.target.checked })} />浏览器直连（需要 MCP 服务允许 CORS）</label><p className="text-[10px] leading-relaxed text-[var(--text-secondary)]">关闭直连时使用米饭机同源代理。代理只接受 HTTPS 或本机开发地址，并限制为 POST JSON-RPC。</p><div className="flex gap-2"><button type="button" onClick={() => setDraft(null)} className="flex-1 rounded-xl border border-[var(--border)] px-3 py-2 text-xs">取消</button><button type="button" onClick={() => { if (!draft.url.trim()) { setMessage("请填写 MCP 地址。"); return; } setMcpSessionToken(draft.id, token); if (persist(draft)) void refreshTools({ ...draft, name: draft.name.trim() || "未命名 MCP", url: draft.url.trim() }); }} className="flex-1 rounded-xl bg-[var(--button-primary-bg)] px-3 py-2 text-xs font-bold text-[var(--button-primary-text)]"><Check className="mr-1 inline h-3.5 w-3.5" />保存并发现</button></div></div></div></div>}
    <a href="https://modelcontextprotocol.io/" target="_blank" rel="noreferrer" className="flex items-center justify-center gap-1 text-[10px] text-[var(--text-secondary)]">MCP 协议说明 <ExternalLink className="h-3 w-3" /></a><span className="sr-only">当前启用服务 {activeCount}</span>
  </div>;
}
