import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { inferCharacterPhoneLocation } from "../src/features/characterPhone/characterPhoneLocation";

const component = readFileSync(new URL("../src/components/AppCharacterPhone.tsx", import.meta.url), "utf8");
const repository = readFileSync(new URL("../src/core/storage/repositories/characterPhoneRepository.ts", import.meta.url), "utf8");
const progression = readFileSync(new URL("../src/features/characterPhone/characterPhoneProgression.ts", import.meta.url), "utf8");
const reaction = readFileSync(new URL("../src/features/characterPhone/characterPhoneReaction.ts", import.meta.url), "utf8");
const thread = readFileSync(new URL("../src/features/characterPhone/characterPhoneThreadService.ts", import.meta.url), "utf8");
const content = readFileSync(new URL("../src/features/characterPhone/characterPhoneContent.ts", import.meta.url), "utf8");
const browserDetails = readFileSync(new URL("../src/features/characterPhone/characterPhoneBrowserDetails.ts", import.meta.url), "utf8");
const location = readFileSync(new URL("../src/features/characterPhone/characterPhoneLocation.ts", import.meta.url), "utf8");
const app = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8");
const store = readFileSync(new URL("../src/components/AppStore.tsx", import.meta.url), "utf8");
const callApp = readFileSync(new URL("../src/features/characterPhone/components/CharacterPhoneCallApp.tsx", import.meta.url), "utf8");
const cameraApp = readFileSync(new URL("../src/features/characterPhone/components/CharacterPhoneCameraApp.tsx", import.meta.url), "utf8");
const gallerySecurity = readFileSync(new URL("../src/features/characterPhone/characterPhoneGallerySecurity.ts", import.meta.url), "utf8");
const verifyPasscodeBlock = component.slice(
  component.indexOf("const verifyPasscode"),
  component.indexOf("const appendUnlockDigit"),
);
const openPhoneBlock = component.slice(
  component.indexOf("function openCharacterPhone"),
  component.indexOf("function formatTime"),
);
const generatePhoneContentBlock = component.slice(
  component.indexOf("const generateCharacterPhoneContent"),
  component.indexOf("const verifyPasscode"),
);

assert.match(component, /选择人物/);
assert.match(component, /忘记密码/);
assert.match(component, /取消并返回桌面/);
assert.match(component, /CHARACTER_PHONE_UNLOCK_PAD/);
assert.match(component, /onOpenChat/);
assert.match(component, /aria-label="角色手机密码"/);
assert.match(component, /failedAttempts >= 5/);
assert.match(component, /failedAttempts:\s*0,\s*lockedUntil:\s*undefined/);
assert.match(component, /advanceCharacterPhone/);
assert.match(component, /setIsAdvancing/);
assert.match(openPhoneBlock, /ensureCharacterPhoneContent/);
assert.doesNotMatch(openPhoneBlock, /advanceCharacterPhone|apiChat/);
assert.match(component, /aria-label="生成角色手机内容"/);
assert.match(generatePhoneContentBlock, /advanceCharacterPhone/);
assert.match(generatePhoneContentBlock, /discoverCharacterPhoneActions/);
assert.match(generatePhoneContentBlock, /generationRequestRef\.current !== requestId/);
assert.match(generatePhoneContentBlock, /Promise\.race/);
assert.match(component, /CHARACTER_PHONE_GENERATION_TIMEOUT_MS/);
assert.doesNotMatch(verifyPasscodeBlock, /advanceCharacterPhone|discoverCharacterPhoneActions/);
assert.match(component, /角色已经知道有人尝试进入/);
assert.match(component, /awarenessLevel/);
assert.match(component, /phone-awareness/);
assert.match(component, /onSendMessage/);
assert.match(component, /messages|browserHistory|diaryEntries/);
assert.match(repository, /storageKeys\.characterPhones/);
assert.match(repository, /phone\.ownerIdentityId === ownerIdentityId[\s\S]*phone\.characterId === characterId/);
assert.match(repository, /loaded\.found && !loaded\.valid/);
assert.match(progression, /lastOpenedAt/);
assert.match(progression, /apiChat/);
assert.match(component, /hidden: !selectedGallery\.hidden/);
assert.match(component, /aria-pressed=\{Boolean\(selectedGallery\.hidden\)\}/);
assert.match(component, /隐藏相册密码/);
assert.match(component, /解锁隐藏相册/);
assert.match(component, /当前测试密码：3737/);
assert.match(component, /overflow-hidden overscroll-none bg-black/);
assert.match(component, /activeApp === "gallery"/);
assert.match(component, /const isGalleryDetail = activeApp === "gallery" && Boolean\(selectedGallery\)/);
assert.match(component, /!isBrowserDetail && !isGalleryDetail/);
assert.match(component, /aria-label="返回相册"/);
assert.match(component, /onPointerDown=\{handleGalleryPointerDown\}/);
assert.match(component, /onPointerUp=\{handleGalleryPointerUp\}/);
assert.match(component, /gallerySequence/);
assert.match(component, /activeApp === "diary" && selectedDiary/);
assert.match(component, /aria-label=\{activeApp === "diary" && selectedDiary \? "返回日记页"/);
assert.match(component, /aria-label="编辑日记"/);
assert.doesNotMatch(component, /‹ 返回/);
assert.match(component, /className="mt-3 min-h-0 flex-1 resize-none border-0 bg-transparent/);
assert.match(component, /aria-label="Google"/);
assert.match(component, /placeholder="搜索或输入网址"/);
assert.match(component, /aria-label="搜索记录"/);
assert.match(component, /管理记录/);
assert.match(component, /onCreateTextImage={handleCharacterPhoneTextImageCreate}/);
assert.match(component, /createCharacterPhoneTextImageDataUrl/);
assert.match(cameraApp, /aria-label="文字图内容"/);
assert.match(cameraApp, /生成文字图/);
assert.match(cameraApp, /onCreateTextImage/);
assert.match(cameraApp, /-mx-5/);
assert.match(component, /activeApp === "diary" \|\| activeApp === "notes" \|\| activeApp === "camera" \? "pb-0"/);
assert.doesNotMatch(cameraApp, /把真实照片留在这里/);
assert.doesNotMatch(cameraApp, /可从设备导入照片；角色手机只保存/);
assert.doesNotMatch(cameraApp, /还没有保存的真实照片/);
assert.match(progression, /createCharacterPhoneTextImageDataUrl/);
assert.match(progression, /主手机里可参考的文字图描述/);
assert.match(progression, /hiddenGalleryTitle/);
assert.match(progression, /isPrivateGalleryEvidence/);
assert.match(progression, /hidden: true/);
assert.match(gallerySecurity, /CHARACTER_PHONE_HIDDEN_GALLERY_TEST_PASSCODE = "3737"/);
assert.match(gallerySecurity, /hiddenGalleryPasscode/);
assert.doesNotMatch(component, /aria-label="分享照片"/);
assert.doesNotMatch(component, /aria-label="下载照片"/);
assert.doesNotMatch(component, /aria-label="更多照片操作"/);
assert.match(component, /deletedAt: Date\.now\(\)/);
assert.match(reaction, /buildCharacterPhoneAwarenessMessage/);
assert.match(reaction, /傲娇|嘴硬/);
assert.match(repository, /threadMessages/);
assert.match(content, /isNpc: true/);
assert.match(thread, /operatedByUser/);
assert.match(thread, /user_edit/);
assert.match(thread, /sourceMessageId/);
assert.doesNotMatch(thread, /shouldUpgradeNpc|phone-thread-reply|聊天记录截图/);
assert.match(content, /groupPattern/);
assert.match(content, /sourceRefs/);
assert.match(progression, /threadMessage/);
assert.match(progression, /threadIncoming/);
assert.match(progression, /threadOutgoing/);
assert.doesNotMatch(content, /createSeedPosts/);
assert.match(component, /朋友圈/);
assert.match(component, /phone-proactive/);
assert.match(component, /PHONE_DESKTOP_APPS/);
assert.match(component, /PHONE_DOCK_APPS/);
assert.match(component, /selectedBrowserEntryId/);
assert.match(component, /setSelectedBrowserEntryId\(item\.id\)/);
assert.match(component, /角色心声/);
assert.match(component, /selectedBrowserDetail\.results\.map/);
assert.match(component, /AI 整理/);
assert.match(component, /返回历史搜索/);
assert.doesNotMatch(component, /简易答案/);
assert.doesNotMatch(component, /把搜索词带回地址栏/);
assert.doesNotMatch(component, /查看原始页面/);
assert.match(component, /rounded-full border border-\[#dfe1e5\]/);
assert.match(component, /buildCharacterPhoneBrowserDetail/);
assert.match(progression, /searchReflection/);
assert.match(progression, /searchResults/);
assert.match(progression, /不同平台/);
assert.match(progression, /短句、停顿、犹豫/);
assert.match(browserDetails, /不是突然想做功课/);
assert.match(component, /CharacterPhoneCallApp/);
assert.match(callApp, /phoneCalls/);
assert.match(component, /chat-tab-nav z-10 box-border flex h-14 min-h-14 max-h-14/);
assert.ok((component.match(/box-border flex h-16 min-h-16 max-h-16/g) || []).length >= 7, "角色手机顶部导航应统一为 64px");
assert.match(callApp, /nav className="box-border grid h-16 min-h-16 max-h-16/);
assert.doesNotMatch(component, /CharacterPhoneLifeEventTag|renderLifeEventTag|同一生活事件/);
assert.doesNotMatch(callApp, /CharacterPhoneLifeEventTag|同一生活事件/);
assert.doesNotMatch(component, /暂无角色日程|没有明确的课程、约定或待办时间/);
assert.doesNotMatch(`${component}\n${callApp}`, /157 0250 3638|138 3548 8102|186 3547 1579/);
assert.match(component, /双时间小组件/);
assert.match(location, /inferCharacterPhoneLocation/);
assert.equal(inferCharacterPhoneLocation(["居住地：东京"], "未知").label, "东京");
assert.equal(inferCharacterPhoneLocation(["所在地：深圳"], "未知").timeZone, "Asia/Shanghai");
assert.match(app, /get\("characterPhoneTest"\) === "1"/);
assert.match(app, /setActiveApp\("character-phone"\)/);
assert.match(app, /ownerIdentityId = input\.ownerIdentityId/);
assert.doesNotMatch(store, /name: "角色手机"/);

console.log("character phone MVP tests passed");
