import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { inferCharacterPhoneLocation } from "../src/features/characterPhone/characterPhoneLocation";

const component = readFileSync(new URL("../src/components/AppCharacterPhone.tsx", import.meta.url), "utf8");
const repository = readFileSync(new URL("../src/core/storage/repositories/characterPhoneRepository.ts", import.meta.url), "utf8");
const progression = readFileSync(new URL("../src/features/characterPhone/characterPhoneProgression.ts", import.meta.url), "utf8");
const reaction = readFileSync(new URL("../src/features/characterPhone/characterPhoneReaction.ts", import.meta.url), "utf8");
const thread = readFileSync(new URL("../src/features/characterPhone/characterPhoneThreadService.ts", import.meta.url), "utf8");
const content = readFileSync(new URL("../src/features/characterPhone/characterPhoneContent.ts", import.meta.url), "utf8");
const location = readFileSync(new URL("../src/features/characterPhone/characterPhoneLocation.ts", import.meta.url), "utf8");
const app = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8");
const store = readFileSync(new URL("../src/components/AppStore.tsx", import.meta.url), "utf8");

assert.match(component, /选择人物/);
assert.match(component, /忘记密码/);
assert.match(component, /取消并返回桌面/);
assert.match(component, /CHARACTER_PHONE_UNLOCK_PAD/);
assert.match(component, /onOpenChat/);
assert.match(component, /aria-label="角色手机密码"/);
assert.match(component, /failedAttempts >= 5/);
assert.match(component, /failedAttempts:\s*0,\s*lockedUntil:\s*undefined/);
assert.match(component, /advanceCharacterPhone/);
assert.match(component, /setIsAdvancing/);
assert.match(component, /角色已经知道有人尝试进入/);
assert.match(component, /awarenessLevel/);
assert.match(component, /phone-awareness/);
assert.match(component, /onSendMessage/);
assert.match(component, /messages|browserHistory|diaryEntries/);
assert.match(repository, /storageKeys\.characterPhones/);
assert.match(repository, /phone\.ownerIdentityId === ownerIdentityId[\s\S]*phone\.characterId === characterId/);
assert.match(progression, /lastOpenedAt/);
assert.match(progression, /apiChat/);
assert.match(component, /hidden: !selectedGallery\.hidden/);
assert.match(component, /deletedAt: Date\.now\(\)/);
assert.match(reaction, /buildCharacterPhoneAwarenessMessage/);
assert.match(reaction, /傲娇|嘴硬/);
assert.match(repository, /threadMessages/);
assert.match(content, /isNpc: true/);
assert.match(thread, /operatedByUser/);
assert.match(thread, /user_edit/);
assert.match(thread, /shouldUpgradeNpc/);
assert.match(thread, /phone-thread-reply/);
assert.match(thread, /聊天记录截图/);
assert.match(progression, /threadMessage/);
assert.match(progression, /threadIncoming/);
assert.match(progression, /threadOutgoing/);
assert.doesNotMatch(content, /createSeedPosts/);
assert.match(component, /朋友圈/);
assert.match(component, /phone-proactive/);
assert.match(component, /PHONE_DESKTOP_APPS/);
assert.match(component, /PHONE_DOCK_APPS/);
assert.match(component, /双时间小组件/);
assert.match(location, /inferCharacterPhoneLocation/);
assert.equal(inferCharacterPhoneLocation(["居住地：东京"], "未知").label, "东京");
assert.equal(inferCharacterPhoneLocation(["所在地：深圳"], "未知").timeZone, "Asia/Shanghai");
assert.match(app, /get\("characterPhoneTest"\) === "1"/);
assert.match(app, /setActiveApp\("character-phone"\)/);
assert.doesNotMatch(store, /name: "角色手机"/);

console.log("character phone MVP tests passed");
