import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { validateForumGeneratedText, validateForumPostStyle, validateForumReplyStyle } from "../src/domain/forum/forumContentSafety";
const source = readFileSync(new URL("../src/features/forum/services/forumGenerationService.ts", import.meta.url), "utf8");
assert.match(source, /情感|校园|都市怪谈|树洞|连载故事/);
assert.doesNotMatch(source, /奇怪经历|微恐悬疑|规则怪谈|幻想种族|宠物邻里|网络社交/);
assert.match(source, /禁止括号动作/);
assert.match(source, /FORUM_REALISM_RULES/);
assert.match(source, /FORUM_REPLY_REALISM_RULES/);
assert.equal(validateForumPostStyle({ title: "今天遇到件事", body: "刚刚在群里看到一句话，有点不知道怎么回，想问问大家会怎么处理？" }).valid, true);
assert.equal(validateForumPostStyle({ title: "第一章：开端", body: "故事开始，后来最终所有人都知道了。" }).valid, false);
assert.equal(validateForumReplyStyle("这楼说得有点道理，我也想问下楼主后面怎么处理的？").valid, true);
assert.equal(validateForumReplyStyle("第一章开始，镜头切到另一个场景，旁白继续解释所有人的心理。").valid, false);
const sanitized = validateForumGeneratedText("（叹气）我发了一张图片");
assert.equal(sanitized.text.includes("叹气"), false, "parenthetical action is removed before persistence");
assert.equal(validateForumGeneratedText("[发送于: 12:00]").valid, false);
assert.equal(validateForumGeneratedText("我朋友遇到一点麻烦，想听听大家意见。 ").valid, true);
console.log("forum content variety tests passed");
