import assert from "node:assert/strict";
import { isExplicitImageRequest, assertImageGenerationTrigger } from "../src/features/chat/services/imageGenerationIntent";
import { createDirectReplyCandidates } from "../src/features/chat/services/directChatService";
import { assertImageGenerationConfiguration, createGeneratedImageMessages } from "../src/features/chat/services/characterImageService";

assert.equal(isExplicitImageRequest("给我发张你现在的照片"), true);
assert.equal(isExplicitImageRequest("小狗小狗，给我发张你的照片"), true);
assert.equal(isExplicitImageRequest("给我发一张自拍"), true);
assert.equal(isExplicitImageRequest("发张照片给我"), true);
assert.equal(isExplicitImageRequest("给我看看你的照片"), true);
assert.equal(isExplicitImageRequest("来张自拍"), true);
assert.equal(isExplicitImageRequest("拍张照片给我"), true);
assert.equal(isExplicitImageRequest("生成一张你的照片"), true);
assert.equal(isExplicitImageRequest("生成一张你在咖啡馆的图片"), true);
assert.equal(isExplicitImageRequest("不要发照片，只和我聊天"), false);
assert.equal(isExplicitImageRequest("我没让你生成图片"), false);
assert.equal(isExplicitImageRequest("他说“给我发张照片”是什么意思？"), false);
assert.equal(isExplicitImageRequest("今天天气不错"), false);
assert.doesNotThrow(() => assertImageGenerationTrigger("manual"));
assert.doesNotThrow(() => assertImageGenerationTrigger("explicit-user-text", "给我看看图片"));
assert.throws(() => assertImageGenerationTrigger("explicit-user-text", "普通聊天"));
assert.throws(() => assertImageGenerationConfiguration({ enableImageGeneration: false } as any, { id: "char", name: "角色", avatar: "", personality: "", backstory: "", enableImageGeneration: true }));
const fakeReply = createDirectReplyCandidates({ rawText: "（发送了一张自拍照片）", disableBracketActions: false, keepPeriods: false, characterId: "char", createId: () => "fake", currentTime: () => 1 });
assert.equal(fakeReply.messages.length, 0, "failed generation must not leave a fake image text message");
const actual = createGeneratedImageMessages({ messageId: "image-1", characterId: "char", imageAssetId: "asset-1", imageMimeType: "image/png", trigger: "explicit-user-text", scope: { kind: "direct", relationId: "rel-1", conversationId: "direct:rel-1" }, timestamp: 1 });
assert.equal(actual.message.imageAssetId, "asset-1");
assert.equal(actual.message.relationId, "rel-1");
assert.equal(actual.message.conversationId, "direct:rel-1");
console.log("imageGenerationIntent.test passed");
