import assert from "node:assert/strict";
import { renderToStaticMarkup } from "react-dom/server";
import { MomentsApp } from "../src/features/moments/MomentsApp";
import { cleanAndExtractMoment, getMomentComments, isMomentSkipResponse, isShortMomentImageDescription, stripMomentVoiceMarkup } from "../src/features/moments/services/momentContent";
import { upsertMomentPreservingOrder } from "../src/features/moments/services/momentState";
import type { Character, Moment, UserSettings } from "../src/types";

const character: Character = { id: "char-a", name: "阿岚", avatar: "avatar.png", personality: "温柔", backstory: "测试" };
const settings: UserSettings = { name: "小林", avatar: "user.png", bio: "测试用户", apiKey: "", selectedModel: "" } as UserSettings;
const moment: Moment = { id: "moment-1", characterId: character.id, authorName: character.name, authorAvatar: character.avatar, content: "今天很开心", timestamp: 1, likes: [settings.name], comments: [], imageDescription: "雨后的街道和一盏温暖的路灯" };
const markup = renderToStaticMarkup(<MomentsApp moments={[moment]} characters={[character]} settings={settings} translations={{}} filterCharacterId={null} onClearFilter={() => undefined} onClose={() => undefined} onAddMoment={() => undefined} onAddComment={() => undefined} onDeleteComment={() => undefined} onLikeMoment={() => undefined} onSaveSettings={() => undefined} onPublishUserMoment={() => undefined} onGenerateMomentImage={async () => undefined} onPublishComment={() => undefined} onUploadImage={async () => undefined} showToast={() => undefined} onMomentTextContextMenu={() => undefined} onMomentTextPointerDown={() => undefined} onMomentTextPointerUpOrLeave={() => undefined} onMomentTextPointerMove={() => undefined} onCommentClick={() => undefined} onCommentPointerDown={() => undefined} onClearCommentLongPress={() => undefined} />);

const parsed = cleanAndExtractMoment("正文\n评论：补充");
assert.equal(parsed.content, "正文");
assert.deepEqual(parsed.selfComments, ["补充"]);
assert.equal(getMomentComments({ ...moment, content: "正文\n评论：补充" }).length, 1);
assert.equal(stripMomentVoiceMarkup("[语音|3]普通文字"), "普通文字");
assert.equal(stripMomentVoiceMarkup("[voice]|3|普通文字"), "普通文字");
assert.equal(stripMomentVoiceMarkup('[语音: "普通文字" (3秒)]'), "普通文字");
assert.equal(isShortMomentImageDescription("车队基地窗外阴雨连绵的天空"), true);
assert.equal(isShortMomentImageDescription("这是一段足够长的文字图描述，用来保持长文本左对齐并且不应该触发居中布局。"), false);
assert.equal(isMomentSkipResponse("[SKIP]"), true);
assert.equal(isMomentSkipResponse("不回复。"), true);
assert.equal(isMomentSkipResponse("我也这么觉得。"), false);
assert.equal(getMomentComments({ ...moment, comments: [{ id: "voice-comment", authorName: "阿岚", authorAvatar: "avatar.png", content: "[voice|3]评论文字", timestamp: 2 }] })[0].content, "评论文字");
assert.ok(markup.includes("今天很开心"));
assert.ok(markup.includes("w-10 h-10 rounded-[6px]"));
assert.ok(markup.includes("生成图片"));
assert.match(markup, />文字图<\/span>/);
assert.match(markup, /aria-label="生成朋友圈图片"/);
assert.ok(markup.includes("items-center justify-center"));
assert.ok(markup.includes("shadow-[0_2px_8px_rgba(15,23,42,0.08)]"));
assert.equal(markup.includes("文字图 · 点击查看"), false);
assert.ok(markup.includes("moments-comment-list") === false);

const newerMoment = { ...moment, id: "moment-newer", timestamp: 2, likes: [], comments: [] };
const imageUpdated = { ...moment, image: "data:image/png;base64,updated", imageType: "photo" as const };
const updatedOrder = upsertMomentPreservingOrder([newerMoment, moment], imageUpdated);
assert.deepEqual(updatedOrder.map((item) => item.id), ["moment-newer", "moment-1"], "updating an old Moment must preserve feed order");
assert.equal(updatedOrder[1].image, "data:image/png;base64,updated");
assert.deepEqual(upsertMomentPreservingOrder([moment], newerMoment).map((item) => item.id), ["moment-newer", "moment-1"], "new Moments still appear at the top");
console.log("PASS moments content normalization, legacy comments, feed card, and preserved class names");
