import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import type { Message } from "../src/types.ts";
import { applyOfflineStoryRegeneration, prepareOfflineStoryRegeneration } from "../src/domain/offlineStory/offlineStoryRegeneration.ts";

const message = (id: string, sender: "user" | "character"): Message => ({
  id,
  characterId: "character-1",
  relationId: "relation-1",
  conversationId: "conversation-1",
  sender,
  content: id,
  timestamp: 1,
  isOffline: true,
});

const messages = [message("before", "user"), message("target", "character"), message("after", "character")];
const context = prepareOfflineStoryRegeneration(messages, "target");
assert.ok(context);
assert.deepEqual(context.history.map((item) => item.id), ["before"]);
assert.deepEqual(context.followingMessages.map((item) => item.id), ["after"]);
assert.deepEqual(applyOfflineStoryRegeneration(context, message("replacement", "character")).map((item) => item.id), [
  "before", "replacement", "after",
]);
assert.equal(prepareOfflineStoryRegeneration(messages, "before"), null, "user-authored nodes cannot be regenerated by AI");

const offline = readFileSync(new URL("../src/components/AppOffline.tsx", import.meta.url), "utf8");
const generationHook = readFileSync(new URL("../src/features/offline/hooks/useOfflineStoryGenerationActions.ts", import.meta.url), "utf8");
const settingsHook = readFileSync(new URL("../src/features/offline/hooks/useOfflineStorySettings.ts", import.meta.url), "utf8");
const menu = readFileSync(new URL("../src/components/offline/OfflineNodeMenu.tsx", import.meta.url), "utf8");
assert.match(menu, /重回信息/);
assert.match(menu, /删除当前节点/);
assert.match(settingsHook, /allowCharacterToSpeakForUser: settingsAllowCharacterToSpeakForUser/);
assert.match(generationHook, /【用户角色控制权】/);
assert.match(generationHook, /禁止替用户生成任何台词/);

console.log("PASS offline node regeneration preserves surrounding plot and user-control setting reaches the generation prompt");
