import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const view = readFileSync(new URL("../src/components/reading/ReadingStoryView.tsx", import.meta.url), "utf8");
const app = readFileSync(new URL("../src/components/AppReading.tsx", import.meta.url), "utf8");
const generation = readFileSync(new URL("../src/features/reading/story/readingStoryGeneration.ts", import.meta.url), "utf8");
const coStoryView = readFileSync(new URL("../src/components/reading/ReadingCoStoryView.tsx", import.meta.url), "utf8");
const coStoryGeneration = readFileSync(new URL("../src/features/reading/story/readingCoStoryGeneration.ts", import.meta.url), "utf8");
assert.match(view, /故事正文/);
assert.match(view, /下一步选项/);
assert.match(view, /输入你的行动/);
assert.match(view, /档案/);
assert.match(view, /情报/);
assert.match(view, /读档/);
assert.match(app, /setReadingStoryBookId/);
assert.match(app, /穿书：进入这本小说的故事宇宙/);
assert.match(generation, /validateReadingStoryTurnResult/);
assert.match(generation, /commitReadingStoryTurn/);
assert.match(generation, /requestId/);
assert.match(generation, /expectedStoryUpdatedAt/);
assert.match(coStoryView, /让 TA 提建议/);
assert.match(coStoryView, /询问 TA 的意见/);
assert.match(coStoryView, /接受/);
assert.match(coStoryView, /拒绝/);
assert.match(coStoryView, /提交我的行动/);
assert.match(coStoryView, /你的视角/);
assert.match(coStoryGeneration, /generateReadingCoStoryAiAction/);
console.log("reading story UI integration checks passed");
