import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const settings = readFileSync("src/components/AppSettings.tsx", "utf8");
const backupPanel = readFileSync("src/features/settings/components/SystemBackupPanel.tsx", "utf8");
const backupActions = readFileSync("src/features/settings/hooks/useSystemBackupActions.ts", "utf8");
const storageHook = readFileSync("src/features/settings/hooks/useStorageHealthActions.ts", "utf8");
const transferHook = readFileSync("src/features/settings/hooks/useSettingsTransferActions.ts", "utf8");
const imageApiHook = readFileSync("src/features/settings/hooks/useSettingsImageApiActions.ts", "utf8");
const textApiHook = readFileSync("src/features/settings/hooks/useSettingsTextApiActions.ts", "utf8");
const voiceActions = readFileSync("src/features/settings/hooks/useSettingsVoiceActions.ts", "utf8");
const connectionActions = readFileSync("src/features/settings/hooks/useSettingsApiConnectionActions.ts", "utf8");
const assetActions = readFileSync("src/features/settings/hooks/useSettingsAssetActions.ts", "utf8");
const presetActions = readFileSync("src/features/settings/hooks/useSettingsPresetActions.ts", "utf8");
const applyPresetAction = readFileSync("src/features/settings/hooks/useSettingsApplyPresetAction.ts", "utf8");
const identityActions = readFileSync("src/features/settings/hooks/useSettingsIdentityActions.ts", "utf8");
assert.match(settings, /SystemBackupPanel/);
assert.doesNotMatch(settings, /id="backup-export-title"/);
assert.match(backupPanel, /id="backup-export-title"/);
assert.match(backupPanel, /onImport/);
assert.match(settings, /useSystemBackupActions/);
assert.match(backupActions, /snapshotSystemBackupIndexedDb/);
assert.match(backupActions, /restoreSystemBackupIndexedDb/);
assert.doesNotMatch(settings, /const handleSystemBackupImport/);
assert.doesNotMatch(settings, /const handleSystemBackupInspect/);
assert.match(settings, /useStorageHealthActions/);
assert.match(storageHook, /migrateContentStorage/);
assert.match(storageHook, /buildStorageDiagnosticReport/);
assert.match(settings, /useSettingsTransferActions/);
assert.match(transferHook, /buildDesktopModuleBackup/);
assert.match(transferHook, /parseDesktopModuleBackup/);
assert.doesNotMatch(settings, /const downloadDesktopModuleBackup/);
assert.doesNotMatch(settings, /const handleExportChatTheme/);
assert.match(settings, /useSettingsImageApiActions/);
assert.match(imageApiHook, /apiFetchImageModels/);
assert.match(imageApiHook, /apiTestImageConnection/);
assert.match(imageApiHook, /persistImagePresetDraft/);
assert.doesNotMatch(settings, /const fetchImageModels/);
assert.doesNotMatch(settings, /const saveImageApiConfig/);
assert.match(settings, /useSettingsTextApiActions/);
assert.match(textApiHook, /apiFetchModels/);
assert.match(textApiHook, /handleSaveApiConfig/);
assert.doesNotMatch(settings, /const handleFetchModels/);
assert.doesNotMatch(settings, /const handleSaveApiConfig/);
assert.match(settings, /useSettingsVoiceActions/);
assert.match(voiceActions, /normalizeMosslandApiEndpoint/);
assert.match(voiceActions, /handleSaveVoiceSettings/);
assert.doesNotMatch(settings, /const handleSaveVoiceSettings =/);
assert.match(settings, /useSettingsApiConnectionActions/);
assert.match(connectionActions, /apiTestKey/);
assert.match(connectionActions, /handleTestConnection/);
assert.doesNotMatch(settings, /const handleTestConnection =/);
assert.match(settings, /useSettingsAssetActions/);
assert.match(assetActions, /compressImagePreservingTransparency/);
assert.match(settings, /\{ key: "character-phone", label: "手机" \}/);
assert.match(assetActions, /input\.value = ""/);
assert.match(assetActions, /onIconStatusChange/);
assert.match(assetActions, /wallpaperSource: "user"/);
assert.match(assetActions, /handleRestoreAllIcons/);
assert.doesNotMatch(settings, /const handleAvatarUpload =/);
assert.match(settings, /useSettingsPresetActions/);
assert.match(presetActions, /themeColor: "#3b82f6"/);
assert.match(presetActions, /handleSaveCurrentAsPreset/);
assert.doesNotMatch(settings, /const handleSaveCurrentAsPreset =/);
assert.match(settings, /useSettingsApplyPresetAction/);
assert.match(applyPresetAction, /CLASSIC_BUBBLE_STRUCTURED_STYLE/);
assert.match(applyPresetAction, /wallpaperSource: "preset"/);
assert.match(applyPresetAction, /const applyPreset =/);
assert.doesNotMatch(settings, /const applyPreset =/);
assert.match(settings, /useSettingsIdentityActions/);
assert.match(identityActions, /activeIdentityId: id/);
assert.match(identityActions, /onSwitchIdentity/);
assert.doesNotMatch(settings, /const handleSwitchIdentity =/);
console.log("PASS system backup presentation is separated from AppSettings business orchestration");
