import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const source = readFileSync(new URL("../src/components/AppChat.tsx", import.meta.url), "utf8");
const contactsStart = source.indexOf("{/* TABS: CONTACTS LIST (通讯录) */}");
const momentsStart = source.indexOf("{/* TABS: MOMENTS FEED (朋友圈) */}", contactsStart);
assert.ok(contactsStart >= 0 && momentsStart > contactsStart);
const contactsSource = source.slice(contactsStart, momentsStart);
assert.match(source, /theme-add-contact-dialog bg-\[var\(--surface\)\] text-\[var\(--text-primary\)\]/);
assert.match(source, /正在以「\{activeIdentityName\}」的身份添加好友/);
assert.match(source, /bg-\[var\(--surface-raised\)\] border border-\[var\(--border\)\] px-3 py-2 text-\[10px\] text-\[var\(--text-secondary\)\]/);
assert.match(source, /button-primary-bg/);
assert.match(source, /button-secondary-bg/);
assert.match(source, /添加好友/);
assert.match(source, /马甲添加/);
assert.doesNotMatch(source, /showAliasContactPicker/);
assert.match(contactsSource, /选择马甲/);
assert.match(contactsSource, /修改马甲/);
assert.match(contactsSource, /border-\[var\(--color-accent\)\] ring-1/);
assert.match(contactsSource, /title="修改马甲"/);
assert.match(contactsSource, /aria-label="保存马甲"/);
assert.match(contactsSource, /aria-label="删除马甲"/);
assert.match(contactsSource, /selectedAliasId/);
assert.match(contactsSource, /getRootIdentityId\(identity\.id, settings\.identities \|\| \[\]\) === activeIdentityRootId/);
assert.doesNotMatch(contactsSource, /border-b border-\[var\(--divider\)\] pb-4/);
assert.doesNotMatch(contactsSource, /aria-label=\{`编辑马甲/);
assert.doesNotMatch(contactsSource, /全部身份/);
assert.doesNotMatch(contactsSource, /添加角色/);
assert.doesNotMatch(contactsSource, /每个马甲拥有独立的联系人/);
console.log("PASS add-contact dialog semantic surfaces preserve the existing identity-aware contact flow");
